//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.0.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package jp.plen.plencheck.services;

import android.content.Context;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class PlenConnectionService_
    extends PlenConnectionService
{

    public static PlenConnectionService_.IntentBuilder_ intent(Context context) {
        return new PlenConnectionService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<PlenConnectionService_.IntentBuilder_>
    {

        public IntentBuilder_(Context context) {
            super(context, PlenConnectionService_.class);
        }
    }
}
